### ISSUE TITLE
Unnesessary info method 

### ISSUE THREAD

**Issue by AshutoshChakraborty** [ChakrabortyAnimesh/GetterSetterMethod#1]
Why you need the info method in Person class?

I thing it is error pron because in info() method you basically call two setter methods 
but what if anyone call the Person object using default constructor then in the info() method it unnable to access the field with is set in info() method using the setter methods 

**Example**

`
Person person=new Person() 
`
`
person.info()
`
internally in the info method 
`public void info(){
`
`
     setName(name)  //??? but where you set the field name anyway
`
`
     setAge(age)  //??? but where you set the field age anyway
`
`
}
`

**Comment by ChakrabortyAnimesh** [comment]
If i add this piece of code into info() method then it will work fine without any error. See the changes in below code :
 public void info(){
       if(name!=null && age!=0) {
           setName(name);
           setAge(age);
           System.out.println("Your name is " + getName() + " and your age is " + getAge());
       }
       else{
           System.out.println("Sorry, Please enter the name and age before you call info method.");
       }
   }

public class Main {
    public static void main(String[] args) {

        Person person1=new Person();
        /*person1.setName("Animesh");
        person1.setAge(19);*/
        person1.info()
    }
}

This code will work even if you call directly info() method before calls the setName() and setAge() method. This will show  a message.
